### ISSUE TITLE
User forced to use the ‘Back’ arrow on the browser to return to the list view after viewing a record

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#101]
The user is forced to use the Back arrow on the browser to return to the list view after viewing a record. In View mode the user has the option to **Edit**, **Make a Copy** or **Remove the Entry**.  They don’t have a **Back** or **Cancel** button.

See **View Catalogue.png** attached. 

**Steps to reproduce:** 	
**1.**	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
**2.**	Enter email and password then select Continue
**3.**	Click on the Browse link 
**4.**	Select View on a previously entered catalogue
**5.**	Attempt to cancel out of the record details

**Actual Result:**	
There is no **Back** button and the user has to select the back arrow on the browser to return to the list view 

**Expected Result:**
User should have a **Back** button or **Cancel** button 

<img width="733" alt="View Catalogue" src="https://user-images.githubusercontent.com/64217737/80369487-443c0200-8886-11ea-9ed4-ead8bd82c69b.png">

**Comment by GerryMartin** [comment]
**NOTE**:  Re-tested.  User now returned to previous screen, i.e. Back to search results or Back to browse catalogue.  Closed.

**Comment by GerryMartin** [comment]
**NOTE**:  Closed in error.  The  **Back to search** results link only displays the first time you view the record.  For example, when you select **View** the link is visible.  However, if you then select **Edit** then **Cancel** to go back to **View catalogue entry** the link is not visible.  Re-open.

**Comment by StephenPatterson-DSS** [comment]
May need to implement breadcrumbs to solve this problem. You can hit the view page from two locations: browse or search. A history of page visits is not maintained currently.

**Comment by GerryMartin** [comment]
Hi Stephen, I have re-tested and this is working well when you **View** or **Edit** a catalogue.  However, the breadcrumbs are not present when you **Edit** and **Link a new Dependency**.  See below. See below.

<img width="414" alt="101" src="https://user-images.githubusercontent.com/64217737/81669044-82682280-943d-11ea-9d27-66a81013410a.png">

**Comment by StephenPatterson-DSS** [comment]
@GerryMartin would you mind closing this one and opening a new bug for this specific issue and I can schedule in a fix for that.

**Comment by GerryMartin** [comment]
@StephenPatterson-DSS Closed this one and raised #165.
