### ISSUE TITLE
The ‘Architecture Portal’ link incorrectly pointing to https://dss-architecture-portal.london.cloudapps.digital

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#102]
The **‘Architecture Portal’** link incorrectly pointing to https://dss-architecture-portal.london.cloudapps.digital/.  See **Architecture Portal.png** attached. 

<img width="656" alt="Architecture Portal" src="https://user-images.githubusercontent.com/64217737/80362986-7300ab00-887b-11ea-945c-28af50ea2520.png">

**Steps to reproduce:** 	
**1.**	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
**2.**	Enter email and password then select Continue
**3.**	Click on the Architecture Portal link 

**Actual Result:**	
Incorrectly pointing to https://dss-architecture-portal.london.cloudapps.digital/

**Expected Result:**
Should point to associated resource on the Staging environment

**Comment by StephenPatterson-DSS** [comment]
Link will default to the production version of the portal. Environment variable used to change link in other environments. (Production version not deployed).

**Comment by GerryMartin** [comment]
Re-tested.  Now linking to environment - staging.  Closed.
