### ISSUE TITLE
QUERY – Should the ‘Make a copy’ functionality include ‘Tags’, ‘Depends on’ and ‘Used by’

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#103]
When the **Make a copy** functionality is used to create a new record, the following are not copied:

**1.**	Tags
**2.**	Depends on
**3.**	Used by

See **Make a copy.png** attached. 

**Steps to reproduce:** 	
**1.**	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
**2.**	Enter email and password then select **Continue**
**3.**	Click on the **Browse** link 
**4.**	Select **View** on a previously entered catalogue
**5.**	Select the **Make a copy** button
**6.**	View details of the copied record

**Actual Result:**	
The following are not copied:
**1.**	Tags
**2.**	Depends on
**3.**	Used by

**Expected Result:**
Unsure.  Confirming if this is correct behaviour. 

<img width="436" alt="Make a Copy" src="https://user-images.githubusercontent.com/64217737/80374909-51a9ba00-888f-11ea-9a37-a6c7de880cbb.png">

**Comment by StephenPatterson-DSS** [comment]
Agreed, if an entry is copied then its user defined tags and dependencies should be copied. The 'Used by' data refers to other entries that link to the this one.

**Comment by JamesONeill-DoF** [comment]
Re-tested. This time, the user defined tags, and 'depends on' entries were replicated across to the copy. This was not the case for the 'used by' entries, which has been confirmed as expected behaviour.

**Comment by GerryMartin** [comment]
Closing.  See James's comments above.
