### ISSUE TITLE
Authentication - Entering an Incorrect UserName results in an Application Error

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#112]
From the Catalogue landing page, attempt to login using incorrect credentials:
Enter a Username which does not exist in the system
Enter a Password which does.
Click "Continue".
An Application error log is presented to the user. 
This should not be the case.

**Comment by JamesONeill-DoF** [comment]
![image](https://user-images.githubusercontent.com/64086276/80470641-32b43200-893a-11ea-99f5-253ad4aedf00.png)

**Comment by StephenPatterson-DSS** [comment]
The application no longer authenticates users directly. Instead a user is authenticated by Cognito and automatically logged in to the application.

**Comment by JamesONeill-DoF** [comment]
This is no longer the case - Cognito Auth enabled. Unable to replicate at re-test. Closing
