### ISSUE TITLE
Architecture Catalogue:  Error changing Status

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#113]
Error when attempting to change **Status**.  See **Edit Error.png** attached. 

**Steps to reproduce:** 	
1.	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
2.	Enter email and password then select **Continue**
3.	Click on the **Browse** link 
4.	Select **View** beside a catalogue
5.	Select the **Edit** button
6.	Select a different Status from the dropdown
7.	Select **Save** **changes**

**Actual Result:**	
Message:  There is a problem.  There was an error auditing your last action.  Please contact support.

**Expected Result:**
Status change should be successful

<img width="852" alt="Edit Error" src="https://user-images.githubusercontent.com/64217737/80479232-9d6b6a80-8946-11ea-89eb-db055a9ccc15.png">

**Comment by StephenPatterson-DSS** [comment]
This was a failure to write to the audit service, probably due to incorrect configuration in the environment at the time. Status changes can be made and audited without error.
