### ISSUE TITLE
Search - The search appears to be caching results (changes to records are not reflected).

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#114]
Searched for a Catalogue entry with Status "approved".
The entry was returned successfully.
Edited the entry to change the status to "unapproved".
Saved changes successfully.
Searched for the same entry again. 
The entry was returned as expected, however the "Status" still showed "approved".
Selected to view the entry. The status change was present in the record (it had saved correctly).

It appears that the search is caching the entry's attributes.

**Comment by StephenPatterson-DSS** [comment]
Unable to replicate this bug.

**Comment by JamesONeill-DoF** [comment]
I'm the same - I've tried to replicate this again today, and have been unable to do so. Can be re-opened if it's encountered again.

**Comment by JamesONeill-DoF** [comment]
I'm unable to replicate this. Closing.
