### ISSUE TITLE
Minor issue with message returned when you attempt to add a duplicate record

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#117]
When attempting to add the same record twice a message is returned informing the user that an entry with this name and version already exists.  However, if you attempt to add again the message displays twice.   See **Problem Text.png** attached. 

**Steps to reproduce:** 	
**1.**	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
**2.**	Enter email and password then select **Continue**
**3.**	Select **Add a new catalogue entry** 
**4.**	Enter details and select **Save new entry**
**5.**	Add a second entry with the same **Name** and **Version**

**Actual Result:**	
**Message**:  ‘An entry with this name and version already exists’ displays twice

**Expected Result:**
Message should only display once

<img width="557" alt="Problem Text" src="https://user-images.githubusercontent.com/64217737/80492338-c5b19400-895b-11ea-9e6b-110f7d076c31.png">

**Comment by JamesONeill-DoF** [comment]
@StephenPatterson-DSS 
Have re-tested this. I'm not sure that it has yet been successfully resolved. Attempting to add a dupe entry with the same name and version, I received the error message presented twice (as before).

**Comment by GerryMartin** [comment]
Yes, it's still happening.

**Comment by StephenPatterson-DSS** [comment]
The messages are different now; each link goes to name or version respectively:
<img width="1031" alt="Screenshot" src="https://user-images.githubusercontent.com/50415815/81147784-f18fd380-8f72-11ea-9281-8d25c3f3b040.png">

**Comment by GerryMartin** [comment]
**NOTE:**  Accepted  - as designed.  Closing.
