### ISSUE TITLE
User can amend a record to show that it depends on itself

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#118]
The user can amend a record to show that it depends on itself.  See **Dependencies.png a**ttached. 

**Steps to reproduce:** 	
**1.**	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
**2.**	Enter email and password then select **Continue**
**3.**	Select **Browse**
**4.**	Select **View** on an existing record
**5.**	Select **Change** beside **Depends on**
**6.**	Select **Add dependency**
**7.**	Search for dependencies
**8.**	Tick the check box beside the name of the record you are amending
**9.**	Select **Link selected entries**

**Actual Result:**	
The catalogue entry will appear to depend on itself 

**Expected Result:**
User should not be able to select the same catalogue entry as a dependency

<img width="904" alt="Dependencies" src="https://user-images.githubusercontent.com/64217737/80494298-6c972f80-895e-11ea-8d93-05099097f74a.png">

**Comment by GerryMartin** [comment]
**NOTE**:  Re-tested.  Can no longer make an entry dependent upon itself.  Message displays: _You cannot** make an entry dependent upon itself_.  However, the message is displaying twice.  Once at top and again in the middle of the dependency list.  See **Dependent upon itself.png** below., 

<img width="720" alt="Dependent upon itself" src="https://user-images.githubusercontent.com/64217737/81073361-6e716d80-8edf-11ea-96a3-b436cd112ac8.png">

**Comment by StephenPatterson-DSS** [comment]
This is by design and follows the pattern for highlighting the item is causing the problem. This is important if there is a list of possible dependencies.

**Comment by GerryMartin** [comment]
Closing as per Stephen's comments above.
