### ISSUE TITLE
The same dependency can be added to record many times

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#119]
The user can add the same dependency to a record numerous times.  See **DuplicatedDependencies.png** attached. 

**Steps to reproduce:** 	
**1.**	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
**2.**	Enter email and password then select **Continue**
**3.**	Select **Browse**
**4.**	Select **View** on an existing record
**5.**	Select **Change** beside **Depends on**
**6.**	Select **Add dependency**
**7.**	Search and select a dependency and **Link selected entries**
**8.**	Select **Change** again
**9.**	Select **Add dependency**
**10.**	Select the same dependency and select **Link selected entries**

**Actual Result:**	
The same dependency can be added numerous times

**Expected Result:**
The same dependency should only be allowed to be added once

<img width="566" alt="Duplicate Dependencies" src="https://user-images.githubusercontent.com/64217737/80495871-5db17c80-8960-11ea-8a73-bf64cc3131ca.png">

**Comment by GerryMartin** [comment]
**NOTE:**  Could the name of the record you are in display at the top of the Dependency List to make it easier for the user to select the correct dependencies?  See **Dependency List** below.

<img width="374" alt="Dependency List" src="https://user-images.githubusercontent.com/64217737/80497054-dcf38000-8961-11ea-9188-13774fa2ddb3.png">

**Comment by GerryMartin** [comment]
**NOTE:**  Re-open.  Now unable to add a duplicate dependency.  However, the new message, 'A dependency between _dependency name_ and _dependency name_ already exists' is displaying twice.  Firstly at the top and secondly in the middle of the dependency list.  See **Duplicate** **Message.png
<img width="720" alt="Duplicate Message" src="https://user-images.githubusercontent.com/64217737/81072764-8d233480-8ede-11ea-91d5-b5e2c86aafbb.png">
** attached.

**Comment by GerryMartin** [comment]
**NOTE**:  Un-ticking the box does not remove the message

**Comment by StephenPatterson-DSS** [comment]
This is the case for all error messages in the application.

**Comment by GerryMartin** [comment]
Closing as per Stephen's comment above.
