### ISSUE TITLE
Accessibility Statement - Contact Details to be Provided

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#124]
The Accessibility statement mentions to 'contact us' if content is required in a specific accessible format. Currently, It's not clear how to make contact.
Contact details to be made available in the page content.

**Comment by StephenPatterson-DSS** [comment]
mail-to link added. A form may be preferable in future.

**Comment by JamesONeill-DoF** [comment]
This has been resolved and re-tested successfully - The statement now contains hyperlinks to the EA Team shared mailbox. Closing.
