### ISSUE TITLE
Landing Page - Search Option to be added as a Default Action

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#125]
For a contributor user, the app landing page currently contains a description of the catalogue, along with the "Add a new catalogue entry" button.

The default action for a user should instead be a search (or a interrogable view of all records). 

As a user, before I’d make a new entry to the catalogue, I’d want to check that it doesn’t already exist.

**Comment by StephenPatterson-DSS** [comment]
New button added to home page.

**Comment by JamesONeill-DoF** [comment]
Button appearing and working as expected. Closing.
