### ISSUE TITLE
New catalogue entry screen - Incorrect validation on the 'Product page URL' field.

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#127]
When creating a new catalogue resource, the 'Product page URL' field contains validation to prevent the entry of URLs starting www.  - This should not be the case.

Secondly, no domain is required to pass validation on this field - so “http://thistestsite” is accepted. This should be prevented.

**Comment by JamesONeill-DoF** [comment]
Re-tested.
URLS beginning "www." could now be entered successfully. URLs beginning "http" and "https", which lacked a domain suffix were prevented from being entered. 
However, pages beginning "www." without a domain suffix were not prevented. 
This seems like an edge case, and the current behaviour may be sufficient for this ticket to be closed.

**Comment by StephenPatterson-DSS** [comment]
Agreed that what was observed is an edge case, so closing.
