### ISSUE TITLE
'Beta' Tag on App pages to be changed to 'Alpha'

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#129]
The app currently presents the following to users:

"beta This is a new service – your feedback will help us to improve it."

This app is currently in Alpha stage, rather than beta. Tag to be updated.

**Comment by StephenPatterson-DSS** [comment]
This tag is controlled by an environment variable and will be changed using CircleCi.

**Comment by JamesONeill-DoF** [comment]
Now resolved successfully. Closing.
