### ISSUE TITLE
Record Views to be Captured in Audit Logs / Usage Tracker

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#130]
As an NICS EA user, I want the ability to see when a user has viewed a catalogue entry.

At present, only Create, Update and Delete actions are being captured. Reads should be, also.

**Comment by StephenPatterson-DSS** [comment]
Only individual full record views are recorded, not records returned as a collection via browse or search.

**Comment by JamesONeill-DoF** [comment]
This appears to be working as expected (the JSON associated with the records viewed appeared in the Audit portal). This will be tested more comprehensively when testing the Audit functionality in detail. Closing.
