### ISSUE TITLE
Error when signing in for first time - welcome email failure

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-catalogue#144]
**Describe the bug**
The application crashes when logging in for the first time using single sign on with a failure reported concerning sending an email via GOV.UK Notify.

**To Reproduce**
1. Attempt to log on for the first time

**Expected behavior**
Taken to home screen and welcome email received.

**Screenshots**
<img width="1123" alt="screenshot" src="https://user-images.githubusercontent.com/50415815/81042214-888f5980-8ea7-11ea-8485-9dad473f6b74.png">

**Additional context**
Occurred in sandbox environment.

**Comment by StephenPatterson-DSS** [comment]
Working in local development - could be an environment issue.

**Comment by StephenPatterson-DSS** [comment]
CircleCI environment variable for GOVUK_NOTIFY_USER_WELCOME_TEMPLATE_ID was not set

**Comment by JamesONeill-DoF** [comment]
![New User Login Error 09 06 20](https://user-images.githubusercontent.com/64086276/84139262-79bc3980-aa47-11ea-9523-984275197a6d.JPG)
Re-tested. Error still encountered.

Steps: Removed user dof-oneillj from the catalogue, using the admin->user management page.

Cleared browser cache, and logged in as that user.


Expected: The application landing page is presented.

Actual: An exception was thrown (see attached screenshot)

**Comment by StephenPatterson-DSS** [comment]
Environment variable typo for GOVUK_NOTIFY_USER_WELCOM_TEMPLATE_ID corrected.

**Comment by StephenPatterson-DSS** [comment]
Email received successfully on account creation.
