### ISSUE TITLE
New search returns a maximum of 10 results

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-catalogue#145]
**Describe the bug**
Search returns a maximum of 10 results

**To Reproduce**
1. Use a common search word that appears in more than 10 entries
2. Click on 'continue'
3. View search results

**Expected behavior**
More than 10 results should be returned

**Screenshots**
<img width="1012" alt="screenshot" src="https://user-images.githubusercontent.com/50415815/81044025-60a1f500-8eab-11ea-90ff-b69eb7cd7514.png">

**Additional context**
Introduced as a result of changing search algorithm (see EntryRepository.php)

**Comment by JamesONeill-DoF** [comment]
I've re-tested this, with a search returning 12 records successfully.
