### ISSUE TITLE
Search - No ordering of results returned

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#148]
Currently, there's no sort being applied to the search results for the Catalogue. There should be.

**Comment by StephenPatterson-DSS** [comment]
Search results are now ordered by a score relating to the closeness of match to the word or phrase entered.

**Comment by StephenPatterson-DSS** [comment]
Look at the code used in GOV.UK PaaS Monthly Billing Statement

**Comment by StephenPatterson-DSS** [comment]
Sort implemented on search results. (Not implemented on browse).

**Comment by StephenPatterson-DSS** [comment]
Bug fixed, marking as resolved again.

**Comment by JamesONeill-DoF** [comment]
Re-tested. I'm not sure that this is working quite right at present. 

I found that searching "VersionSearch 1" Returned a list of related results, however, those entries containing the text "VersionSearch" appeared at the bottom of the list. Is it possible that this is sorting on closeness ASC, rather than DESC? 

Similar behaviour was observed when searching "D Test 1 x" (which should have been an exact match) - the three catalogue entries beginning "D Test..." appeared halfway down the list of results returned.

**Comment by StephenPatterson-DSS** [comment]
The sort by relevance was removed when sort by column functionality was introduced. I suspect you are seeing a sort by name and version as default.
