### ISSUE TITLE
Search - Ability to search by version number

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#149]
As a developer user, I want the ability to search the Catalogue by specific version number, in order to  straightforwardly locate the resource I'm looking for.

**Comment by StephenPatterson-DSS** [comment]
A combination of name and version number has been added to the Elasticsearch index. Search results are now ranked in order of how closely they match the search term rather than alphabetically.

**Comment by JamesONeill-DoF** [comment]
Re-tested. 
Searched for Name - All versions returned as expected.
Searched for version, only - Specific version was returned, along with other entries with the same version.
Searched for Name and Version - Only the exact match was returned. 
Searched for multiple version formats. Results were returned as expected.
Appears to be working as expected. Closing the ticket.
