### ISSUE TITLE
Search - Wildcard search not working if * is used as a prefix

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#150]
The wildcard only works if appended to the end of the search term, It doesn't work when used at the start.

For example, searching for _JamesTestEntry_ using _JamesTest*_ returns the result as expected. Searching against _*TestEntry_ returns no results.

**Comment by StephenPatterson-DSS** [comment]
Further investigation required into Elasticsearch functionality. Being deferred to a later release
