### ISSUE TITLE
Dependencies - Warning to be provided to user if the Status of dependent app is other than approved

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#151]
Currently, users can add a dependency to any catalogue entry, regardless of that entry's status.

Users should be prompted with a warning where the status of the dependency being added is other than approved.

This warning should not prevent the user from proceeding.

**Comment by StephenPatterson-DSS** [comment]
Label added to dependency search results to show status of each entry found

**Comment by JamesONeill-DoF** [comment]
Re-tested. When creating a dependency, the user is now provided a warning for each of the search results returned, where the status is other than approved. Checked for each available status. The user was not prevented from linking. Working as expected. Closing.
