### ISSUE TITLE
Remove 'opens in new window icon' for external links

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-catalogue#176]
**Is your feature request related to a problem? Please describe.**
Remove 'opens in new window icon' for external links

**Describe the solution you'd like**
Remove 'opens in new window icon' for external links

**Describe alternatives you've considered**
Using words in the link itself

**Additional context**
https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/

**Comment by StephenPatterson-DSS** [comment]
Back buttons also removed as a result of comparison with GOV.UK guidance.

**Comment by JamesONeill-DoF** [comment]
These have been removed. This can be closed.
