### ISSUE TITLE
Add styling to header

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-catalogue#177]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The header banner colour is associated with the service.

**Describe alternatives you've considered**
nidirect colour scheme

**Additional context**
None

**Comment by JamesONeill-DoF** [comment]
The header Banner now largely matches that used on gov.uk (inherits from gov.uk css). Should it be exactly the same? (E.g., Colour of the highlight bar immediately under the banner is still distinct). Sufficient to close this?

**Comment by StephenPatterson-DSS** [comment]
Styling across apps and websites will need to be rationalised. However closing this issue for now.
