### ISSUE TITLE
Wildcard (*) search does not work for searching to add dependencies

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#183]
When adding a dependency to an existing record, the user performs a search for the entry to link to.
This search does not currently allow the user to search using the wildcard character (*). When using the character, no results are returned.

**Comment by StephenPatterson-DSS** [comment]
Unable to reproduce in current version. May have be fixed as a result of a previous bug fix.

**Comment by JamesONeill-DoF** [comment]
Appears to be resolved. Wildcard search returned entries as expected. Closing.
