### ISSUE TITLE
Admin Screen - Stephen P's email appears associated with each of the account entries

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#189]
On the Admin screen, Stephen's email address appears associated with each of the Account entries. This should not be the case.

**Comment by StephenPatterson-DSS** [comment]
Email address was incorrectly hard coded.

**Comment by JamesONeill-DoF** [comment]
This has now been resolved. Re-tested by viewing multiple entries, then by removing and re-adding a user. The email address presented was specific to the user on each occasion. Closing.
