### ISSUE TITLE
New users logging in for the first time are being presented with an error screen.

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#191]
![Error on login](https://user-images.githubusercontent.com/64086276/82560535-8c8acf00-9b69-11ea-8392-ea2bd3af0e8f.jpg)

I created a new user, using an alias of my NIGOV email address. Having entered my cognito pin to verify my account and log in, I was presented an error screen (see attached). Refreshing the page presented me the application landing page as expected.

**Comment by JamesONeill-DoF** [comment]
![New User Login Error 09 06 20](https://user-images.githubusercontent.com/64086276/84141319-e97ff380-aa4a-11ea-9444-d33d141a87c7.JPG)
Believe that this issue likely has the same root cause as #144 .
Using a brand new user to create an account and log in, I'm no longer seeing the error page shown in the original attachment. Instead, I'm now thrown an exception (see newly attached screenshot).

**Comment by StephenPatterson-DSS** [comment]
Problem was with environment variables for APP_URL, SESSION_DOMAIN and NICS_EA_COGNITO_URL
