### ISSUE TITLE
Redundant "related_sbbs" field appearing in the Audit JSON object. To be removed.

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#204]
A redundant 'related_sbbs' field is appearing in the audit log JSON objects associated with the Catalogue. 
It's consistently populated with null. 
As this field is not being used, it should be removed.

**Comment by StephenPatterson-DSS** [comment]
Redundant attribute hidden from audit. Perhaps this attribute should be completely removed.

**Comment by JamesONeill-DoF** [comment]
Re-tested, by viewing the Audit entries associated with each of the previous milestone 1.0 re-tests. This attribute was not present on any of the entries viewed. Closing.
