### ISSUE TITLE
Architecture Catalogue:  Unable to open the ‘Architecture Portal’ link under the ‘Related Resources’ section 

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#211]
Unable to open the Architecture Portal link under the Related Resources section.  See **Architecture Portal link.png** attached. 

**Steps to reproduce:** 	
1.	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
2.	Select the Architecture Portal link under the Related Resources section

**Actual Result:	
This Site cannot be reached**
The web page at https://portal.ea.digitlani.gov.uk/ might be temporarily down or it may have moved permanently to a new web address

**Expected Result:**
Link should open successfully

<img width="529" alt="Architecture Portal link" src="https://user-images.githubusercontent.com/64217737/82997914-ec1c2b00-9ffe-11ea-82c9-22f7a64009af.png">

**Comment by StephenPatterson-DSS** [comment]
As expected, portal is not live yet.

**Comment by GerryMartin** [comment]
**NOTE** As expected.  Closing.
