### ISSUE TITLE
Add description of status

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-catalogue#215]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Home page should describe the meaning of the various statuses.
- approved: approved for use
- unapproved: can only be used with a dispensation
- prohibited: must not be used
- retiring: currently in use but you should plan to replace
- evaluating: can not be used at present but is under consideration

**Describe alternatives you've considered**
None

**Additional context**

**Comment by StephenPatterson-DSS** [comment]
Descriptive text added including a table of definitions.

**Comment by JamesONeill-DoF** [comment]
Have checked this. While the on-page descriptions do not match those above, verbatim, the meanings are the same. This can be closed out.
