### ISSUE TITLE
Add functionality to enable or disable usage tracking

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-catalogue#65]
Add functionality to enable or disable usage tracking via environment variable

**Comment by StephenPatterson-DSS** [comment]
Usage tracking can be toggled by NICS_EA_USAGE_TRACKING_ENABLED env variable.

NB. While test it was noticed that usage tracking events had been failing because of a switch to queueing events. This event cannot be queued as it relies on the users identity token; these events are fired immediately now.

**Comment by JamesONeill-DoF** [comment]
I don't think that this can be re-tested at present. The Usage Tracker is failing to display any results. Ticket for this issue logged, here: 
https://github.com/dof-dss/ea-usageTracking-gui/issues/9

**Comment by JamesONeill-DoF** [comment]
Have re-checked this again this morning - The Usage Service GUI is still failing to load results.

**Comment by StephenPatterson-DSS** [comment]
Closing. Tested in development.
