### ISSUE TITLE
Site Links Not Opening In New Windows (regardless of destination). Back Buttons Not Present.

### ISSUE THREAD

**Issue by JamesONeill-DoF** [dof-dss/architecture-catalogue#89]
No 'back' button exists on the "Get Support" screen. Should there be one here?

**Comment by JamesONeill-DoF** [comment]
This is also the case on the Accessibility, Cookies, and Privacy policy pages. Note, this would likely not be a problem if they were open in new tabs (they don't presently).

**Comment by JamesONeill-DoF** [comment]
Updating this ticket to serve as a 'catch-all bucket' for this issue across the app. Same domain pages should open in the same tab and should have a back button available, external locations should open in new tabs, and have the new tab icon associated with them.

**Comment by StephenPatterson-DSS** [comment]
Same domain pages open in same tab with a back button. External location open in a new tab and have the nidirect style external link icon beside them.

**Comment by StephenPatterson-DSS** [comment]
Just found latest research on this: https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/.

This may need to be backed out.

**Comment by JamesONeill-DoF** [comment]
Re-tested - This is now behaving in the way which was expected when the ticket was logged.
At first read of the linked blog post, my understanding is that GDS are talking about removal of the seperate 'external link' icon, rather than the 'opens in a new window' icon. Happy to discuss further. Closing the ticket for now.
