### ISSUE TITLE
Architecture Catalogue:  Fields presented to the user differ in Add, View and Edit modes

### ISSUE THREAD

**Issue by GerryMartin** [dof-dss/architecture-catalogue#99]
The fields presented to the user differ in **Add**, **View** and **Edit** modes.  For example, User Defined Tags are available in **View** but not in **New** or **Edit** mode.  The user can add/change tags in **View** mode but not in New or Edit mode.  

In this example should User defined tags not be available in Add and Edit mode but not available **View** mode?  

In addition, Category and Sub-category are separate fields in View mode but combined for both New and Edit mode.  Is this expected behaviour?

See attached table. 

[Fields.xlsx](https://github.com/dof-dss/architecture-catalogue/files/4538797/Fields.xlsx)
**Steps to reproduce:** 	
1.	Launch https://architecture-catalogue.staging.ea.digitalni.gov.uk/home
2.	Enter email and password then select Continue
3.	Select Browse
4.	Select Add a new catalogue entry and take note of the fields available
5.	Select View on an existing record and take note of the fields available
6.	Click View on one of the records and select Edit and take note of the fields available 

**Actual Result:**	
1.  Fields different depending on Add, View or Edit mode
2.  User can change details in view mode

**Expected Result:**

1. 	The fields displayed should be the same in each mode
2.	User should not be able to change details in View mode, instead they should use Edit

**Comment by StephenPatterson-DSS** [comment]
This behaviour is by design and follows a GDS pattern.

A combined drop down is used to input category and sub-category by design.

**Comment by GerryMartin** [comment]
**NOTE**:   See Stephen's comments above.  By design. Closing.
